include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    avoid_types_on_closure_parameters: false
    public_member_api_docs: false
