include: package:dart_test_tools/package.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
  errors:
    included_file_warning: ignore

linter:
  rules:
    avoid_types_on_closure_parameters: false
