include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    avoid_slow_async_io: false
    avoid_types_on_closure_parameters: false
    comment_references: false
