include: package:dart_test_tools/package.yaml
plugins:
  dart_test_tools: ^7.3.0
analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
linter:
  rules:
    avoid_types_on_closure_parameters: false
    document_ignores: false
    require_trailing_commas: false
