name: Continuos Integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      platforms: '["linux","windows","macos"]'
      buildRunner: true
      extendedAnalyzerArgs: --linter test-import # Do not run the lib-export linter
      unitTestPaths: test/unit
      coverageExclude: >-
        "**/*.g.dart"
        "**/*.freezed.dart"
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "bash tool/ci/setup_linux.sh",
          "macos": "bash tool/ci/setup_macos.sh",
          "windows": "powershell tool/ci/setup_windows.ps1"
        }

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    with:
      releaseRef: refs/heads/master
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
