name: Continuos Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      platforms: '["linux","windows","macos"]'
      buildRunner: true
      publishExclude: '["lib/src/.gitignore"]'
      unitTestPaths: test/unit
      coverageExclude: >-
        "**/*.g.dart"
        "**/*.freezed.dart"
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "dart run tool/ci_install_flutter.dart",
          "windows": "dart run tool/ci_install_flutter.dart",
          "macos": "dart run tool/ci_install_flutter.dart"
        }

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      releaseRef: refs/heads/master
      buildRunner: true
      publishExclude: '["lib/src/.gitignore"]'
    secrets:
      PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
